name: ecommerce_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0
#-------------------- PACKAGES ---------------------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages

  # ICONS
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Managment
  get: ^4.7.3

 #--------------- google fonts -----------
  google_fonts: ^6.3.0


  # Product Specific



  #------------ PACKAGES END ------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  #------------ LOCAL ASSETS ----------------
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/